name: QuickItemsGenerator
version: 1.0
main: me.opkarol.quickitemgenerator.QuickItemGenerator
api-version: 1.16
authors: [ ThisOpKarol ]
description: Generate your items with lore, name, enchants quick!

commands:
  qig:
